-- Seed Data for HashCodeLab Website
USE hashcodelab_db;

-- Clear existing data
TRUNCATE TABLE blog_posts;
TRUNCATE TABLE projects;
TRUNCATE TABLE testimonials;

-- Insert Blog Posts
INSERT INTO blog_posts (id, title, slug, excerpt, content, category, author, image, published_date, tags) VALUES
(UUID(), 'Top 10 Web Design Trends in 2025', 'web-design-trends-2025', 'Discover the latest web design trends shaping the digital landscape in 2025.', '<p>The web design landscape is constantly evolving, and 2025 brings exciting new trends that combine aesthetics with functionality. Here are the top 10 trends you need to know about.</p><h2>1. AI-Powered Personalization</h2><p>Websites now adapt in real-time to user preferences using artificial intelligence.</p><h2>2. 3D Elements and Immersive Experiences</h2><p>Three-dimensional graphics are becoming mainstream, creating engaging user experiences.</p>', 'Web Design', 'Sarah Johnson', 'https://images.unsplash.com/photo-1559028012-481c04fa702d?w=800', NOW(), '["web design", "trends", "UI/UX"]'),
(UUID(), 'How AI is Transforming Business Operations', 'ai-transforming-business', 'Explore how artificial intelligence is revolutionizing the way businesses operate.', '<p>Artificial Intelligence is no longer just a buzzword. It\'s actively transforming how businesses operate across all industries.</p><h2>The AI Revolution</h2><p>From customer service chatbots to predictive analytics, AI is making businesses smarter and more efficient.</p><h2>Real-World Applications</h2><p>Companies are using AI for inventory management, customer insights, and process automation.</p>', 'Technology', 'Michael Chen', 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800', NOW(), '["AI", "business", "automation"]'),
(UUID(), 'SEO Best Practices for 2025', 'seo-best-practices-2025', 'Master the essential SEO strategies to boost your website\'s visibility in 2025.', '<p>Search Engine Optimization continues to be crucial for online visibility. Here are the best practices for 2025.</p><h2>Content Quality Over Quantity</h2><p>Focus on creating valuable, in-depth content that truly helps your audience.</p><h2>Mobile-First Indexing</h2><p>Google prioritizes mobile-optimized websites, so ensure your site performs perfectly on all devices.</p>', 'SEO', 'Emily Rodriguez', 'https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800', NOW(), '["SEO", "digital marketing", "strategy"]');

-- Insert Projects
INSERT INTO projects (id, title, slug, category, description, client, technologies, image, images, problem, solution, results, testimonial) VALUES
(UUID(), 'E-Commerce Platform for Fashion Brand', 'fashion-ecommerce', 'Web Development', 'A modern e-commerce platform with advanced filtering and seamless checkout experience.', 'StyleHub Fashion', '["React", "Node.js", "MongoDB", "Stripe"]', 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800', '["https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800"]', 'StyleHub needed a modern e-commerce platform to replace their outdated system and handle high traffic during sales.', 'We built a scalable React-based platform with advanced product filtering, real-time inventory management, and integrated payment processing.', '250% increase in online sales, 60% faster page load times, and 95% customer satisfaction rating.', 'HashCodeLab delivered beyond our expectations. The new platform transformed our business!'),
(UUID(), 'Fitness Tracking Mobile App', 'fitness-tracker-app', 'Mobile App', 'Cross-platform fitness app with workout tracking and social features.', 'FitLife Solutions', '["React Native", "Firebase", "Redux"]', 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800', '["https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800"]', 'FitLife wanted to create an engaging fitness app that would motivate users and build a community.', 'We developed a cross-platform mobile app with workout tracking, progress analytics, and social sharing features.', '100K+ downloads in first 3 months, 4.8 star rating, and featured in App Store.', 'The app exceeded all our goals. The user engagement is phenomenal!'),
(UUID(), 'Brand Identity for Tech Startup', 'tech-startup-branding', 'Graphic Design', 'Complete brand identity including logo, colors, and marketing materials.', 'InnovateTech', '["Adobe Illustrator", "Photoshop", "Figma"]', 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800', '["https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800"]', 'InnovateTech needed a professional brand identity to establish credibility in the competitive tech market.', 'We created a modern, memorable brand identity with a comprehensive style guide and marketing collateral.', 'Brand recognition increased by 300%, successful funding round achieved.', 'The brand identity perfectly captures our vision and values.'),
(UUID(), 'AI Customer Support Chatbot', 'ai-chatbot', 'AI Solutions', 'Intelligent chatbot for automated customer support with natural language processing.', 'RetailPro', '["Python", "TensorFlow", "NLP", "API Integration"]', 'https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800', '["https://images.unsplash.com/photo-1531746790731-6c087fecd65a?w=800"]', 'RetailPro struggled with high customer support costs and slow response times.', 'We implemented an AI-powered chatbot that handles common queries and seamlessly transfers complex issues to human agents.', '70% reduction in support costs, 24/7 availability, 85% issue resolution rate.', 'This chatbot has revolutionized our customer service operations!'),
(UUID(), 'Real Estate Listing Portal', 'real-estate-portal', 'Web Application', 'Comprehensive property listing platform with advanced search and virtual tours.', 'HomeSeeker Realty', '["Vue.js", "Laravel", "MySQL", "Google Maps API"]', 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800', '["https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800"]', 'HomeSeeker needed a modern platform to showcase properties and streamline the buying process.', 'We developed a feature-rich web application with virtual tours, mortgage calculator, and advanced search filters.', '400% increase in property inquiries, 50% faster sale closures.', 'The platform has transformed how we do business. Simply outstanding!'),
(UUID(), 'Restaurant Website & Ordering System', 'restaurant-ordering', 'Web Development', 'Modern website with online ordering and table reservation system.', 'Gourmet Bistro', '["React", "Express.js", "PostgreSQL", "Stripe"]', 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800', '["https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800"]', 'Gourmet Bistro wanted to offer online ordering and streamline their reservation process.', 'We created a beautiful website with integrated online ordering, table reservations, and loyalty program.', '180% increase in online orders, reduced wait times, improved customer experience.', 'Our revenue has grown significantly thanks to the new ordering system!');

-- Insert Testimonials
INSERT INTO testimonials (id, name, company, position, content, image, rating) VALUES
(UUID(), 'Sarah Mitchell', 'TechVision Inc', 'CEO', 'HashCodeLab transformed our digital presence completely. Their team is professional, creative, and delivers on time. Highly recommended!', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200', 5),
(UUID(), 'James Anderson', 'Global Solutions Ltd', 'CTO', 'Working with HashCodeLab was a game-changer for our business. They understood our vision and brought it to life with exceptional quality.', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200', 5),
(UUID(), 'Emily Chen', 'StartUp Ventures', 'Founder', 'The best IT services company we\'ve worked with. Their expertise in modern technologies and attention to detail is unmatched.', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200', 5),
(UUID(), 'Michael Rodriguez', 'E-Commerce Pro', 'Director of Technology', 'HashCodeLab delivered our e-commerce platform ahead of schedule. The result exceeded our expectations in every way.', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200', 5),
(UUID(), 'Lisa Thompson', 'Creative Agency Co', 'Managing Director', 'Outstanding service! The team at HashCodeLab is talented, responsive, and truly cares about client success. A pleasure to work with.', 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=200', 5);
